const THOUSAND = 1000;
const MILLION = THOUSAND * THOUSAND;
function thousand(n) {
  return Math.round(n * 1000);
}
function million(n) {
  return Math.round(n * 1000000);
}


export default function () {
  return [{
    language: 'Aja',
    region: 'African',
    speakers: thousand(550),
    pangrams: ['Agbetɔwo pleŋu vanɔ gbɛmɛ ko vovoɖeka gbeswɛgbeswɛ, sɔto amɛnyinyi ko acɛwo gomɛ; wo xɔnɔ susunywin ko jimɛnywi so esexwe. Wo ɖo a wa nɔvi ɖaɖa wowo nɔnɔwo gbɔ. '],
  },
  {
    language: 'Aghem',
    region: 'African',
    speakers: thousand(27),
    specialCharacters: 'À Â È Ê Ì Î Ò Ô Ù Û à â è ê ì î ò ô ù û Ā ā Ē ē Ě ě Ī ī Ŋ ŋ Ō ō Ū ū Ɔ Ɛ Ɨ Ǎ ǎ Ǐ ǐ Ǒ ǒ Ǔ ǔ Ʉ ɔ ɛ ɨ ʉ ʔ',
  },
  {
    language: 'Akan',
    region: 'African',
    speakers: million(32),
    specialCharacters: 'Ɛ ɛ Ɔ ɔ Á á É é Ɛ́ ɛ́ Í í Ḿ ḿ Ń ń Ó ó Ɔ́ ɔ́ Ú ú À à È è Ɛ̀ ɛ̀ Ì ì M̀ m̀ Ǹ ǹ Ò ò Ɔ̀ ɔ̀ Ù ù',
    paragraphs: ['Dèdé: Èhé nà Kégyétíá wó? Méfá kwáń béǹ só ákó hó? Kyèí: Kò w’àníḿ tèè kòsí sè wóbéhúnú sòtóò bí áà yéátwéré àníḿ sé ‘Ònyàmé túmí’.'],
  },
  {
    language: 'Asturian',
    region: 'European',
    speakers: thousand(351),
    opentypeTag: 'AST ',
    specialCharacters: 'Ḥ ḥ Ḷ ḷ',
    paragraphs: [
      'Tolos seres humanos nacen llibres y iguales en dignidá y drechos y, pola mor de la razón y la conciencia de so, han comportase hermaniblemente los unos colos otros.'
    ],
  },
  {
    language: 'Armenian',
    region: 'Caucasian',
    speakers: million(6.7),
    opentypeTag: 'HYE ',
    script: 'Armn',
    pangrams: [
      'Բել դղյակի ձախ ժամն օֆ ազգությանը ցպահանջ չճշտած վնաս էր եւ փառք։',
      'Չին ֆիզիկոսը օճառաջուր ցողելով բժշկում է հայ գնդապետի փքված ձախ թևը:',
    ],
    paragraphs: [
      'Ամբողջագրերի ակնհայտ կիրառություններից զատ՝ տառատեսակների ներկայացում, հաղորդալարերի միջոցով գրվածքի փոխանցման ստուգում, տպիչ մեքենաների փորձարկում և այլն, առաջարկվում էր այն օգտագործեկ ծածկագրության մեջ:',
      'Ճապոներենում «Իրոխա» ամբողջագիրը կիրառվում է որպես այբբենական շարվածքի համարժեքներից մեկը XI դարից սկսած:',
    ],
    alphabet: 'Ա ա Բ բ Գ գ Դ դ Ե ե Զ զ Է է Ը ը Թ թ Ժ ժ Ի ի Լ լ Խ խ Ծ ծ Կ կ Հ հ Ձ ձ Ղ ղ Ճ ճ Մ մ Յ յ Ն ն Շ շ Ո ո Չ չ Պ պ Ջ ջ Ռ ռ Ս ս Վ վ Տ տ Ր ր Ց ց Ւ ւ Փ փ Ք ք Օ օ Ֆ ֆ ՈՒ ու ԵՒ և',
  },
  {
    language: 'Azeri',
    altNames: ['Azerbaijani'],
    region: 'European',
    speakers: million(23),
    pangrams: ['Zəfər, jaketini də papağını da götür, bu axşam hava çox soyuq olacaq.'],
  },
  {
    language: 'Basaa',
    altNames: ['Basa'],
    region: 'African',
    speakers: thousand(300),
    specialCharacters: 'Â È É Ê Ì Í Î Ò Ó Ô Ù Ú Û à á â è é ê ì í î ò ó ô ù ú û Ā ā Ē ē Ě ě Ī ī Ń ń Ŋ ŋ Ō ō Ū ū Ɓ ɓ Ɔ ɔ Ɛ ɛ Ǎ ǎ Ǐ ǐ Ǒ ǒ Ǔ ǔ Ǹ ǹ',
  },
  {
    language: 'Belarusian',
    region: 'European',
    speakers: million(7.6),
    script: 'Cyrl',
    pangrams: ['Літаратурная мова абслугоўвае (паралельна з рускай) розныя сферы дзейнасці беларускага народа, з\'яўляецца поліфункцыянальнай.'],
  },
  {
    language: 'Berber languages',
    region: 'African',
    speakers: 0,
    script: 'Latn',
    specialCharacters: 'Č Ḍ Ɛ Ǧ Ɣ Ḥ Ř Ṛ Ṣ Ṭ Ẓ č ḍ ɛ ǧ ɣ ḥ ř ṛ ṣ ṭ ẓ',
  },
  {
    language: 'Breton',
    region: 'European',
    speakers: thousand(210),
    pangrams: ['Yec’hed mat Jakez ! Skarzhit ar gwerennoù-mañ, kavet e vo gwin betek fin ho puhez.'],
    specialCharacters: 'Â â Ê ê Î î Ñ ñ Ô ô Û û Ù ù Ü ü',
  },
  {
    language: 'Bulgarian',
    region: 'European',
    speakers: million(9),
    script: 'Cyrl',
    pangrams: ['Фучейки и хълцайки, кьоравият грухтящ шопар жадно стъпка зюмбюлите.', 'Ах чудна българска земьо, полюшвай цъфтящи жита.', 'Жълтата дюля беше щастлива, че пухът, който цъфна, замръзна като гьон.', 'Под южно дърво, цъфтящо в синьо, бягаше малко пухкаво зайче. '],
  },
  {
    language: 'Catalan',
    region: 'European',
    speakers: million(4.1),
    pangrams: ['«Dóna amor que seràs feliç!». Això, il·lús company geniüt, ja és un lluït rètol blavís d’onze kWh. aïllament'],
    gotchas: [
      {
        topic: 'punt volat',
        tags: ['metrics', 'contextual', 'localization'],
        description: 'Localized variants of <em>periodcentered</em>, visually centered between two letters <em>L</em> and <em>l</em>, respectively.',
        tests: [
          'il·lús cal·lígraf sibil·la ombrel·la novel·la metàl·lic',
          'IL·LÚS CAL·LÍGRAF SIBIL·LA OMBREL·LA NOVEL·LA METÀL·LIC',
        ],
      }
    ],
  },
  {
    language: 'Croatian',
    region: 'European',
    speakers: million(5.6),
    pangrams: ['Gojazni đačić s biciklom drži hmelj i finu vatu u džepu nošnje.'],
  },
  {
    language: 'Czech',
    speakers: million(10),
    region: 'European',
    pangrams: ['Loď čeří kýlem tůň obzvlášť v Grónské úžině.'],
    gotchas: [{
      topic: 'vertical caron',
      tags: ['metrics'],
      description: 'The vertical form of the caron diacritic found with <em>d</em> and <em>t</em> should be kerned against lowercase letters and punctuation.',
      tests: [
        'loďka ďábelska ďatlov ďábel objížďka buďto',
        'břeťa cenťák žesťový řiťka opúšťať hradišťský tchaj-ťi šťuka dvanásťročný',
        'loď. loď, loď: loď; loď- loď? loď!',
        'dešť. dešť, dešť; dešť: dešť- dešť? dešť!',
        'ď” ľ” ť” ď“ ľ“ ť“',
      ],
    }, {
      topic: 'ring above',
      tags: ['congruency'],
      description: 'It might be preferred that the ring above <em>u</em> (the Czech <em>kroužek</em> diacritic) be congruent with the Scandinavian ring above <em>a</em>, for the rare occasions where Scandinavian proper names are inflected in Czech or Slovak.',
      tests: ['Håkanův?'],
    }],
  },
  {
    language: 'Dagbani',
    region: 'African',
    speakers: thousand(1160),
    alphabet: '’ A a B b CH ch D d E e Ɛ ɛ F f G g GB gb Ɣ ɣ H h I i J j K k KP kp L l M m N n NY ny Ŋ ŋ O o Ɔ ɔ P p R r S s SH sh T t U u W w Y y Z z Ʒ ʒ',
  },
  {
    language: 'Danish',
    speakers: million(5.5),
    region: 'European',
    pangrams: ['Quizdeltagerne spiste jordbær med fløde, mens cirkusklovnen Walther spillede på xylofon.'],
  },
  {
    language: 'Duala',
    region: 'African',
    speakers: thousand(87),
    specialCharacters: 'Á É Í Ó Ú á é í ó ú Ŋ ŋ Ū ū Ɓ Ɔ Ɗ Ɛ ɓ ɔ ɗ ɛ',
  },
  {
    language: 'Dutch',
    region: 'European',
    speakers: million(21),
    pangrams: ['Pa’s wijze lynx bezag vroom het fikse aquaduct.'],
    gotchas: [{
      topic: 'IJ',
      tags: ['ligature', 'optional'],
      tests: ['IJburg Rijksmuseum'],
    }, {
      topic: 'ij-acute',
      tags: ['ligature', 'localization', 'contextual'],
      tests: ['Wíjze'],
    }],
    specialCharacters: "IJ ij Á É Í Ó Ú á é í ó ú ÍJ íj",
  },
  {
    language: 'English',
    region: 'European',
    speakers: million(360),
    pangrams: ['Amazingly few discotheques provide jukeboxes.', 'Why shouldn’t a quixotic Kazakh vampire jog barefoot?', 'Battle of Thermopylae: Quick javelin grazed wry Xerxes.', 'Quick zephyrs blow, vexing daft Jim.', 'Two driven jocks help fax my big quiz.', 'Show mangled quartz flip vibe exactly.', 'Public junk dwarves hug my quartz fox.', 'Jumbling vext frowzy hacks PDQ.', 'Nymphs blitz quick vex dwarf jog.', 'Schwarzkopf vexed Iraq big-time in July.', 'Boxers had zap of gay jock love, quit women.', 'Fix problem quickly with galvanized jets.', 'Watch “Jeopardy!”, Alex Trebek’s fun TV quiz game.'],
    letterings: ['Attaboy Bubble Cache Dwindle Essence Flyleaf Grunge Headache Infinite Jinjer Kinky Lonely Murmur Norwegian Officious Purpose Qashqai Rarity Sognefjord’s Testy Usual Vivian Woodwind Xerxes Yuppy Zanzibar'],
    paragraphs: ['Unicode just made its new emoji list for 2019 official, and the update adds 230 new symbols, including a yawning face, white heart, and pinching hand symbol.',
      'This nomination will be examined in 2009 by the responsible UNESCO Committee.',
      'Reinstate the 17 trainees to flight status. — I will...but I just want you to understand...that I-',
      'Had to be me. Someone else might have gotten it wrong.',
      'Galactica, the Cylon is now flying formation with me! Right above my head. This thing is acting weird...',
    ],
    numerals: ['Unicode just made its new emoji list for 2019 official, and the update adds 230 new symbols, including a yawning face, white heart, and pinching hand symbol.', 'Though the list of new emoji has now been finalized, it will still be several months before the update hits your phone. Unicode will release the update in March, but it will take some time after that for apps and operating systems to roll out support for the new characters. Updates will start hitting in April and continue through the end of the year, according to Emojipedia.'],
    smallcaps: ['Private Johnson went <span style="font-variant-caps: all-small-caps;">AWOL</span> after he received an order to join major combat forces in Iraq.', 'Developing apps requires a knowledge of <span style="font-variant-caps: all-small-caps;">html</span> and JavaScript, and that\'s it.', 'This nomination will be examined in 2009 by the responsible <span style="font-variant-caps: all-small-caps;">UNESCO</span> Committee.'],
    specialCharacters: '', // empty, allows alphabet to be auto-generated
    optionalCharacters: '', /* todo: include letters with diereses and others used in common loans */
  },
  {
    language: 'Ewe',
    region: 'African',
    speakers: million(6.5),
    pangrams: ['Ʋu axaléɖiƒe. Wo dona Eʋegbe le Ghana kple Togo kpakple Benin Dahumey dukɔ siwo le Afrika ƒe ɣetoɖoƒe lɔƒo la me. Gbe gbɔgblɔ siwo teɖe Eʋegbe ŋu wonye Fɔŋgbe kpakple Adzágbe. Esiawo katã wonye Gbe siwo doƒome kple Ʋegbe. Ŋɔŋlɔdzesi blaetɔ̃ ye le Eʋegbe me.'],
    alphabet: 'A a Á á À à Ã ã B b D d Ɖ ɖ E e É é È è Ẽ ẽ Ɛ ɛ F f Ƒ ƒ G g Ɣ ɣ H h X x I i Í í Ì ì Ĩ ĩ K k L l M m N n Ŋ ŋ O o Ó ó Ò ò Õ õ Ɔ ɔ P p R r S s T t U u Ú ú Ù ù Ũ ũ V v Ʋ ʋ W w Y y Z z',
  },
  {
    language: 'Ewondo',
    region: 'African',
    speakers: thousand(580),
    pangram: '',
    specialCharacters: 'À Á Â È É Ê Ì Í Î Ò Ó Ô Ù Ú Û à á â è é ê ì í î ò ó ô ù ú û Ě ě Ń ń Ŋ ŋ Ɔ Ə Ɛ Ǎ ǎ Ǐ ǐ Ǒ ǒ Ǔ ǔ Ǹ ǹ ɔ ə ɛ',
  },
  {
    language: 'Esperanto',
    speakers: 1000,
    pangrams: ['Eble ĉiu kvazaŭ-deca fuŝĥoraĵo ĝojigos homtipon.'],
  },
  {
    language: 'Estonian',
    region: 'European',
    speakers: million(1.1),
    pangrams: ['Põdur Zagrebi tšellomängija-följetonist Ciqo külmetas kehvas garaažis'],
  },
  {
    language: 'Finnish',
    region: 'European',
    speakers: million(5),
    pangrams: ['Fahrenheit ja Celsius yrjösivät Åsan backgammon-peliin, Volkswagenissa, daiquirin ja ZX81:n yhteisvaikutuksesta.'],
  },
  {
    language: 'Fon',
    region: 'African',
    speakers: million(2.2),
    pangrams: ['Ee nyi ɖɔ hɛnnu ɖokpo mɛ ɔ, mɛ ɖokpoɖokpo ka do susu tɔn, bɔ acɛ ɖokpo ɔ wɛ mɛbi ɖo bo e ma sixu kan fɛn kpon é ɖi mɛɖesusi jijɛ, hwɛjijɔzinzan, kpodo fifa ni tiin nu wɛkɛ ɔ bi e ɔ.'],
    todo: 'todo',
    _letterings: ['Gbeta Gbɛ Ɔ Bi Tɔn Ee Ɖɔ Xó Dó Acɛ E Gbɛtɔ Ɖó Kpodo Sisi E Ɖo Na Ɖó N\'I Lɛ Kpo Wu E Wexwle'],
  },
  {
    language: 'French',
    speakers: million(75),
    region: 'European',
    pangrams: ['Voix ambiguë d’un cœur qui au zéphyr préfère les jattes de kiwi.'],
    html: [`M<span style="font-feature-settings: 'sups' 1;">lle</span> Orane`],
    gotchas: [{
      topic: 'iï ïl',
      tags: ['metrics'],
      tests: ['thaïlandais aïllament acneïforme sjiïete thaïlandais aïllament increïblement caraïbes caraïbische privilegiïn geïdentifiseer haïfa geïllustreerd tchaïkovski'],
    }, {
      topic: "d'A L'A l'A",
      tags: ['metrics'],
      tests: ["curly quotes: d’A L’A l’A, straight quotes: d'A L'A l'A"],
    }],
    specialCharacters: 'À à Â â Æ æ Ç ç É é È è Ê ê Ë ë Î î Ï ï Ô ô Œ œ Ù ù Û û Ü ü Ÿ ÿ',
  },
  {
    language: 'West Frisian',
    altNames: ['Western Frisian'],
    region: 'European',
    speakers: thousand(470),
    pangrams: ['Alve bazige froulju wachtsje op dyn komst'],
    specialCharacters: 'Á Ä É Ë Ì Ï Ò Ö Ú Ü á ä é ë ì ï ò ö ú ü Ỳ ỳ',
  },
  {
    language: 'Fula',
    altNames: ['Fulah'],
    region: 'African',
    speakers: million(24),
    pangrams: ['Musidɓe tedduɓe, Fulɓe e leƴƴi kala gonɗi e Fuuta, haa Dakaar, e gure Senegaal kala, mi salminii on calminaali tedduɗi. abɓcdɗefghijklmnŋɲ(ñ)oprstuwyƴ\'ɠ ABƁCDƊEFGHIJKLMNŊƝ(Ñ)OPRSTUWYƳ\'Ɠ'],
  },
  {
    language: 'German',
    speakers: million(95),
    region: 'European',
    pangrams: ['Victor jagt zwölf Boxkämpfer quer über den großen Sylter Deich.'],
    specialCharacters: 'Ä Ö Ü ä ö ü ß ẞ',
  },
  {
    language: 'Greek',
    altNames: ['Modern Greek'],
    script: 'Grek',
    region: 'European',
    speakers: million(12),
    pangrams: ['Ξεσκεπάζω τὴν ψυχοφθόρα βδελυγμία.', 'Ζαφείρι δέξου πάγκαλο, βαθῶν ψυχῆς τὸ σῆμα.', 'Ταχίστη αλώπηξ βαφής ψημένη γη, δρασκελίζει υπέρ νωθρού κυνός.', 'Διαφυλάξτε γενικά τη ζωή σας από βαθειά ψυχικά τραύματα.'],
    paragraphs: [],
    letterings: ['Αμαζόνιος Βραβεία Γουάνγκ Διόδωρος Εργαλεία Ζεμτσούζινα Ηγησιππος Θεοξενιος Ιστορία Καζακστάν Λαμπροκλης Μάρμαρο Νίζνι Ξέρξης Οινομαχος Περσέπολη Ροτόρ Σθενελαος Ταυτιστεί Υπάρχουν Φρολόφ Χοχλόφ Ψαρρής Ωφελιων'],
    numbers: ['Έχει θερμοκρασία τήξης 304°C και θερμοκρασία βρασμού 1473°C.', 'Το φυσικό οξυγόνο αποτελείται από τρία (3) σταθερά ισότοπα: το <sup>16</sup>O (σε ποσοστό 99,762&nbsp;%), το <sup>17</sup>O και το <sup>18</sup>O.'],
    alphabet: 'Α α Β β Γ γ Δ δ Ε ε Ζ ζ Η η Θ θ Ι ι Κ κ Λ λ Μ μ Ν ν Ξ ξ Ο ο Π π Ρ ρ Σ σ ς Τ τ Υ υ Φ φ Χ χ Ψ ψ Ω ω',
  },
  {
    language: 'Guarani',
    script: 'Latn',
    speakers: million(4.6),
    region: 'American',
    paragraphs: ['Mayma yvypóra ou ko yvy ári iñapyty\'yre ha eteĩcha tecoruvicharendá ha acatúape jeguerekópe; ha ikatu rupi oikuaa ñetéva ha añete\'yva, iporãva ha ivaíva, tekotevẽ pehenguéicha oiko oñondivekuéra.'],
    alphabet: 'A a Ã ã Ch ch E e Ẽ ẽ G g G̃ g̃ H h I i Ĩ ĩ J j K k L l M m Mb mb N n Nd nd Ng ng Nt nt Ñ ñ O o Õ õ P p R r Rr rr S s T t U u Ũ ũ V v Y y Ỹ ỹ \'',
  },
  {
    language: 'Hausa',
    region: 'African',
    speakers: million(34),
    paragraphs: ['Nonuwana sun cika sun yi nauyi Suna begen hannayenka Kai kadai ka iya rikesu Tamkar kana rike da kwai Kai ka iya murza su kamar amaro Ka iya shan su kamar lemu Yaya zanyi da raina?', 'Ai ba sauran budurci a tare da nonuwa na Tun ranar da ka ba su ʼyanci Basu san kowa ba sai kai.'],
    alphabet: 'A a B b Ɓ ɓ C c D d Ɗ ɗ E e F f G g H h I i J j K k Ƙ ƙ L l M m N n O o R r R̃ r̃ S s Sh sh T t Ts ts U u W w Y y (Ƴ ƴ) Z z ʼ',
  },
  {
    language: 'Hungarian',
    speakers: million(13),
    region: 'European',
    pangrams: ['Jó foxim és don Quijote húszwattos lámpánál ülve egy pár bűvös cipőt készít.'],
  },
  {
    language: 'Icelandic',
    region: 'European',
    speakers: thousand(300),
    pangrams: ['Sævör grét áðan því úlpan var ónýt.', 'Svo hölt, yxna kýr þegði jú um dóp í fé á bæ.'],
    gotchas: [{
      topic: 'fþ',
      tags: ['metrics', 'ligature'],
      tests: ['hafþór'],
    }],
  },
  {
    language: 'Igbo',
    region: 'African',
    speakers: million(25),
    pangrams: ['Nne, nna, wepụ he’l’ụjọ dum n’ime ọzụzụ ụmụ, vufesi obi nye Chukwu, ṅụrịanụ, gbakọọnụ kpaa, kwee ya ka o guzoshie ike; ọ ghaghị ito, nwapụta ezi agwa.'],
  },
  {
    language: 'Indonesian',
    speakers: million(43),
    region: 'Asian',
    pangrams: ['Muharjo seorang xenofobia universal yang takut pada warga jazirah, contohnya Qatar.'],
    specialCharacters: "",
  },
  {
    language: 'Irish',
    speakers: thousand(150),
    region: 'European',
    pangrams: ['Ċuaiġ bé ṁórṡáċ le dlúṫspád fíorḟinn trí hata mo ḋea-ṗorcáin ḃig'],
  },
  {
    language: 'Italian',
    region: 'European',
    speakers: million(59),
    pangrams: ['Pranzo d’acqua fa volti sghembi.'],
    gotchas: [{
      topic: "d'A L'A l'A",
      tags: ['metrics'],
      tests: ["curly quotes: d’A L’A l’A, straight quotes: d'A L'A l'A"],
    }],
    specialCharacters: "À à É é È è Ì ì Ó ó Ò ò Ù ù",
  },
  {
    language: 'Jula',
    altNames: ['Dyula', 'Dioula'],
    region: 'African',
    speakers: million(2.2),
    alphabet: 'A a B b C c D d E e Ɛ ɛ F f G g H h I i J j K k L l M m N n Ɲ ɲ Ŋ ŋ O o Ɔ ɔ P p R r S s T t U u V v W w Y y Z z',
  },
  {
    language: 'Kabyle',
    region: 'African',
    speakers: million(5.5),
    opentypeTag: 'KAB0',
    pangrams: ['Yiwen wass, Ğeḥḥa yefka-yas baba-s frank, akken ad d-yaɣ aqerruy n tixsi. Yuɣ-it-id, yečča akk aksum-is. Yeqqim-d uceqlal d ilem, yewwi-yas-t-id i baba-s. Ihi, mi t-iwala yenna-yas: "acu-t wa?" yenna-yas: "d aqerruy n tixsi". – A ccmata, anida llan imeẓẓuɣen-is?'],
  },
  {
    language: 'Kako',
    region: 'African',
    speakers: thousand(120),
    specialCharacters: 'À Á Â È É Ê Ì Í Î Ò Ó Ô Ù Ú Û à á â è é ê ì í î ò ó ô ù ú û Ŋ ŋ Ɓ Ɔ Ɗ Ɛ Ǌ ǋ ǌ ɓ ɔ ɗ ɛ',
  },
  {
    language: 'Khoekhoe',
    region: 'African',
    speakers: thousand(200),
    script: 'Latn',
    paragraphs: ['ǃGâi tsēs. ǃGâi ǁgoas. Nē ǀkharib ǃnâ da ge ǁgûn tsî ǀgaen tsî doan tsîn; tsî ǀnopodi tsî ǀkhenadi tsî ǀhuigu tsî ǀamin tsîn; tsî ǀkharagagu ǀaon tsîna ra hō.'],
    alphabet: 'A a B b Ɓ ɓ C c D d Ɗ ɗ E e Ə ə F f G g H h I i J j K k L l M m N n Ŋ ŋ O o P p R r S s T t U u V v W w Y y Z z Ã ã Ẽ ẽ Ə̃ ə̃ ĩ Ĩ Õ õ',
    specialCharacters: 'Ɓ ɓ Ɗ ɗ Ə ə Ŋ ŋ Ã ã Ẽ ẽ Ə̃ ə̃ Ĩ ĩ Õ õ',
  },
  {
    language: 'Koyraboro Senni',
    altNames: ['Koyraboro Senni Songhai'],
    region: 'African',
    speakers: thousand(430),
    specialCharacters: 'Ã Õ ã õ Ŋ ŋ Š š Ž ž Ɲ ɲ Ẽ ẽ',
  },
  {
    language: 'Koyra Chiini',
    altNames: ['Koyra Chiini Songhay'],
    region: 'African',
    speakers: thousand(240),
    specialCharacters: 'Ã Õ ã õ Ŋ ŋ Š š Ž ž Ɲ ɲ Ẽ ẽ',
  },
  {
    language: 'Latin',
    speakers: 0,
    region: 'European',
    pangrams: ['Sic fugiens, dux, zelotypos, quam Karus haberis.'],
    specialCharacters: "",
  },
  {
    language: 'Latvian',
    region: 'European',
    speakers: million(1.5),
    pangrams: ['Muļķa hipiji mēģina brīvi nogaršot celofāna žņaudzējčūsku.', 'Glāžšķūņa rūķīši dzērumā čiepj Baha koncertflīģeļu vākus.'],
    gotchas: [{
      topic: 'ī',
      tags: ['metrics'],
      tests: ['spēcīgi līdz Cīrulis peisaistīja Irbītis Skatīt vadība ierādīta piedalījās dīšas čīča \n"ī" /ī/ \\ī\\ (ī) [ī] {ī}'],
    }],
  },
  {
    language: 'Lingala',
    region: 'African',
    speakers: million(15),
    paragraphs: ['Tatá wa bísó, ozala o likoló, bato bakúmisa Nkómbó ya Yɔ́, bandima bokonzi bwa Yɔ́, mpo elingo Yɔ́, basálá yangó o nsé, lokóla bakosalaka o likoló Pésa bísó lɛlɔ́ biléi bya mokɔlɔ na mokɔlɔ, límbisa mabé ma bísó, lokóla bísó tokolimbisaka baníngá. Sálisa bísó tondima masɛ́nginyá tê, mpe bíkisa bísó o mabé. Na yɔ́ bokonzi, nguyá na nkembo, o bileko o binso sékô. Amen.'],
  },
  {
    language: 'Lithuanian',
    speakers: million(3.1),
    region: 'European',
    pangrams: ['Įlinkdama fechtuotojo špaga sublykčiojusi pragręžė apvalų arbūzą'],
  },
  // { language: 'Lojban', pangram: '.o’i mu xagji sofybakni cu zvati le purdi' },
  {
    language: 'Maasai',
    altNames: ['Masai'],
    region: 'African',
    speakers: million(1.3),
    alphabet: 'a b ch d e ɛ g h i ɨ j k l m n ny ŋ o ɔ p r rr s sh t u ʉ w wu y yi \' ʔ',
  },
  {
    language: 'Macedonian',
    region: 'European',
    speakers: million(2),
    script: 'Cyrl',
    pangrams: ['Ѕидарски пејзаж: шугав билмез со чудење џвака ќофте и кељ на туѓ цех.'],
  },
  {
    language: 'Maltese',
    region: 'European',
    speakers: thousand(520),
    script: 'Latn',
    pangrams: ["L-Unjoni hija mibnija fuq il-valuri ta' rispett għad-dinjità tal-bniedem, ta' libertà, ta' demokrazija, ta' ugwaljanza, ta' l-istat tad-dritt u tar-rispett għad-drittijiet tal-bniedem, inklużi d-drittijiet ta' persuni li jagħmlu parti minn minoranzi. Dawn il-valuri huma komuni għall-Istati Membri f'soċjetà karatterizzata mill-pluraliżmu, in-non-diskriminazzjoni, it-tolleranza, il-ġustizzja, is-solidarjetà u l-ugwaljanza bejn in-nisa u l-irġiel."],
  },
  {
    language: 'Mapudungun',
    region: 'American',
    speakers: thousand(300),
    pangrams: ['Gvxam mincetu apocikvyeh: ñizol ce mamvj ka raq kuse bafkeh mew', 'Ngütram minchetu apochiküyeṉ: ñidol che mamüll ka rag kushe ḻafkeṉ mew.', 'Gütxam minchetu apochiküyenh: ñizol che mamüll ka raq kushe lhafkenh mew.'],
  },
  {
    language: 'Marshallese',
    region: 'Austronesian',
    speakers: 55000,
    script: 'Latn',
    opentypeTag: 'MAH ',
    htmlTag: 'mh',
    pangrams: ['E-ar den̄ōt er. N̄a i-j yokwe ajiri ro nej-ū. em̧m̧an io̧kwe ļalem M̧aaj M̧aļo-eļap '],
    alphabet: 'A a Ā ā B b D d E e I i J j K k L l Ļ ļ M m M̧ m̧ N n Ņ ņ N̄ n̄ O o O̧ o̧ Ō ō P p R r T t U u Ū ū W w',
    gotchas: [
      {
        topic: 'cedilla',
        tags: ['localization'],
        description: 'Marshallese support requires combining <em>cedilla</em> with letters <em>M</em> and <em>O</em>, as no precomposed codepoints exist for these letters. Furthermore, <em>L</em> and <em>N</em> cedilla accents are preferred to be rendered with actual <em>cedilla</em>s, and not <em>comma</em> accents as required for Latvian usage. The cedilla should be centered below all letters, including <em>M</em> and <em>N</en>',
        tests: ['katļo̧k Ļaņtōn M̧ajeļ'],
      },
    ],
  },
  {
    language: 'Mongolian',
    speakers: million(5.2),
    region: 'Asian',
    script: 'Cyrl',
    pangrams: ['Щётканы фермд пийшин цувъя. Бөгж зогсч хэльюү.'],
  },
  {
    language: 'Mundang',
    region: 'African',
    speakers: thousand(240),
    script: 'Latn',
    alphabet: 'A a Ã ã B b Ɓ ɓ C c D d Ɗ ɗ E e Ẽ ẽ Ə ə Ə̃ ə̃ F f G g H h I i Ĩ ĩ J j K k L l M m N n Ŋ ŋ O o Õ õ P p R r S s T t U u V v W w Y y Z z',
  },
  {
    language: 'Ngiemboon',
    region: 'African',
    speakers: thousand(250),
    script: 'Latn',
    specialCharacters: 'À Á Â È É Ê Ì Í Ò Ó Ô Ù Ú Û à á â è é ê ì í ò ó ô ù ú û ÿ Ě ě Ń ń Ŋ ŋ Ÿ Ɔ  Ɛ Ǎ ǎ Ǒ ǒ Ǔ ǔ Ʉ ɔ ɛ ʉ ʼ Ḿ ḿ Ẅ ẅ',
  },
  {
    language: 'Ngomba',
    region: 'African',
    speakers: 63000,
    script: 'Latn',
    specialCharacters: 'Á Â Í Î Ú Û á â í î ú û Ń ń Ŋ ŋ Ɔ Ɛ Ǎ ǎ Ǐ ǐ Ǔ ǔ Ǹ ǹ Ʉ ɔ ɛ ʉ Ḿ ḿ Ẅ ẅ Ꞌ ꞌ',
  },
  {
    language: 'Norwegian',
    speakers: million(4.5),
    region: 'European',
    pangrams: ['Jeg begynte å fortære en sandwich mens jeg kjørte taxi på vei til quiz'],
  },
  {
    language: 'Polish',
    region: 'European',
    speakers: million(40),
    pangrams: ['Koń i żółw grali w kości z piękną ćmą u źródła.'],
    letterings: ['Aerofłot Bóbr Część Ćmić Dyndasz Ernest Farfocel Gringo Hochsztapler Irbis Jajko Krokus Lalka Łękotka Mąkami Nanizać Obrok Ósemka Poprzestań Quiz Rzeżączka Schniesz Świąt Tarty Uzurpator Victoria Warszawa Xero Yeti Złorzeczyć Źrebak Żółtko'],
    gotchas: [{
      topic: 'łł',
      tags: ['metrics'],
      description: 'The łł combination an sometimes produces a busy area. A spacing, kerning or ligature solution is possible should the problem arise.',
      tests: ['Kołłątaj Piłka Ełk Półkole Półton PÓŁTON Radziwiłłów'],
    }],
    specialCharacters: 'Ą ą Ć ć Ę ę Ł ł Ń ń Ó ó Ś ś Ź ź Ż ż',
  },
  {
    language: 'Portuguese',
    region: 'European',
    speakers: million(215),
    pangrams: ['Luís argüia à Júlia que «brações, fé, chá, óxido, pôr, zângão» eram palavras do português.'],
  },
  {
    language: 'Romanian',
    region: 'European',
    speakers: million(24),
    pangrams: ['Bând whisky, jazologul șprițuit vomă fix în tequila.'],
    gotchas: [{
      topic: 'șț',
      tags: ['localization', 'optional'],
      description: 'Consider substituting s-cedilla and t-cedilla with s-comma-below and t-comma-below for Romanian.',
      tests: ['șprițuit (comma) = şpriţuit (cedilla)?'],
    }],
  },
  {
    language: 'Russian',
    region: 'European',
    speakers: million(155),
    script: 'Cyrl',
    pangrams: ['— Любя, съешь щипцы, — вздохнёт мэр, — Кайф жгуч!'],
    paragraphs: ['Я только в главную мысль мою верю. Она именно состоит в том, что люди, по закону природы, разделяются вообще на два разряда: на низший (обыкновенных), то есть, так сказать, на материал, служащий единственно для зарождения себе подобных, и собственно на людей, то есть имеющих дар или талант сказать в среде своей новое слово... Первый разряд всегда — господин настоящего, второй разряд — господин будущего. Первые сохраняют мир и приумножают его численно; вторые двигают мир и ведут его к цели. И те, и другие имеют совершенно одинаковое право существовать. Одним словом, у меня все равносильное право имеют, и — vive la guerre eternelle, — до Нового Иерусалима, разумеется!'],
    letterings: ['Аудиограф Бомбист Втузовец Гуглить Драгдилер Евгения Ё-моё Жоржет Звёздно Иберийский Йельский Классика Льяло Мнемоник Нутационный Ожогин Пилоправ Рэппер Сфинкс Тлить Узуфрукт Фуфачёв Холедох Цугцванг Чёлочка Шропшир Щадящий Ынахсыт Эмвэдэшник Ююба Ягьяев'],
    alphabet: 'А а Б б В в Г г Д д Е е Ё ё Ж ж З з И и Й й К к Л л М м Н н О о П п Р р С с Т т У у Ф ф Х х Ц ц Ч ч Ш ш Щ щ Ъ ъ Ы ы Ь ь Э э Ю ю Я я',
  },
  {
    language: 'Scottish Gaelic',
    speakers: thousand(57),
    region: 'European',
    pangrams: ['Mus d’fhàg Cèit-Ùna ròp Ì le ob.'],
  },
  {
    language: 'Serbian',
    script: 'Cyrl',
    region: 'European',
    speakers: million(19),
    region: 'European',
    pangrams: ['Љубазни фењерџија чађавог лица хоће да ми покаже штос.', 'Ајшо, лепото и чежњо, за љубав срца мога дођи у Хаџиће на кафу.'],
  },
  {
    language: 'Serbian',
    script: 'Latn',
    region: 'European',
    speakers: million(19),
    pangrams: ['Ljubazni fenjerdžija čađavog lica hoće da mi pokaže štos.'],
  },
  {
    language: 'Shilha',
    altNames: ['Tachelhit'],
    region: 'African',
    speakers: million(7),
    script: 'Latn',
    pangrams: ['Lqqiṣt n yan urgaz lli yzznzan tammnt ɣ ssuqq. Yan urgaz iɛmmr mnnaw yilmawn n tammnt ɣ ssuqq. Yašk nn dars yan urgaz, ira ad dars isɣ tammnt. Inna y as: "Mnšk at tzznzt tammnt ann?" Inna y as: "Mḍi tt, iɣ ak tɛžb ar gis tsawalt." Yasy urgaz ann yan yilm, ifsi t, imḍi tammnt, ifk t i bab nns, inna as: "Amẓ, ar kiɣ gussɣ wayyaḍ." Yamẓ t s ufus nns, yasi daɣ umsaɣ lli wayyaḍ, ifsi t, imḍi tammnt, ifk t daɣ i bab nns. Yamẓ t s ufus nns yaḍnin, yasy umsaɣ yan yilm n tammnt, irur. Iggammi bu tammnt mad a yskar i yilmawn lli yumẓ.'],
  },
  {
    language: 'Slovak',
    region: 'European',
    speakers: million(5.5),
    pangrams: ['Kŕdeľ šťastných ďatľov učí pri ústí Váhu mĺkveho koňa obhrýzať kôru a žrať čerstvé mäso.'],
    gotchas: [{
      topic: 'vertical caron',
      tags: ['metrics'],
      description: 'The vertical form of the caron diacritic found with <em>d</em>, <em>L</em>, <em>l</em> and <em>t</em> should be kerned against lowercase letters and punctuation.',
      tests: [
        'loďka ďábelska ďatlov ďábel objížďka buďto',
        'Ľadovec Ľudovít ĽM ',
        'veľký ľuľkovité Iľja Akýkoľvek Teľa Diaľnica',
        'břeťa cenťák žesťový řiťka opúšťať hradišťský tchaj-ťi šťuka dvanásťročný',
        'loď. loď, loď: loď; loď- loď? loď!',
        'čmeľ. čmeľ, čmeľ; čmeľ: čmeľ- čmeľ? čmeľ!',
        'dešť. dešť, dešť; dešť: dešť- dešť? dešť!',
        'ď” ľ” ť” ď“ ľ“ ť“',
      ],
    }, {
      topic: 'caron and inverted caron',
      tags: ['congruency'],
      tests: ['môže?'],
    }],
  },
  {
    language: 'Slovenian',
    speakers: million(2.5),
    region: 'European',
    pangrams: ['Hišničin bratec vzgaja polže pod fikusom.'],
  },
  {
    language: 'Spanish',
    region: 'European',
    speakers: million(405),
    letterings: ['Alacrán Babélico Calcaño Dónde Erección Érebo Fitófago Galápago Hechicería Ilegítimo Índice Jujeño Kafkiano Lilongüe Máximo Neptuno Ñisñil Octógono Óxido Púrpura Recurrir Senescalía Taoísta Urubú Último Vivencia Wawarón Xeneixe Yinyang Zaquizamí'],
    pangrams: ['Whisky bueno: ¡excitad mi frágil pequeña vejez!', 'El pingüino Wenceslao hizo kilómetros bajo exhaustiva lluvia y frío; añoraba a su querido cachorro.', 'La niña, viéndose atrapada en el áspero baúl índigo y sintiendo asfixia, lloró de vergüenza; mientras que la frustrada madre llamaba a su hija diciendo: “¿Dónde estás Waleska?”.', 'El veloz murciélago hindú comía feliz cardillo y kiwi. La cigüeña tocaba el saxofón detrás del palenque de paja.'],
    gotchas: [{
      topic: 'question inverted',
      tags: ['metrics'],
      tests: ['“¿Vale?” «¿Vale?»'],
    }],
  },
  {
    language: 'Swedish',
    region: 'European',
    speakers: million(8.7),
    pangrams: ['Byxfjärmat föl gick på duvshowen.'],
  },
  {
    language: 'Tagalog',
    region: 'Austronesian',
    speakers: million(28),
    opentypeTag: 'TGL ',
    pangrams: ['Ang bawat rehistradong kalahok sa patimpalak ay umaasang magantimpalaan ng ñino.'],
  },
  {
    language: 'Turkish',
    region: 'European',
    speakers: million(63),
    pangrams: ['Pijamalı hasta yağız şoföre çabucak güvendi. Öküz ajan hapse düştü yavrum, ocağı felç gibi.'],
    gotchas: [
      {
        topic: 'Dotted/dotless i',
        tags: ['localization'],
        description: 'Small caps and all-caps fonts need special consideration for Turkic languages, which map lowercase <em>i</em> to uppercase <em>Idotaccent</em>, and uppercase <em>I</em> to lowercase <em>dotlessi</em>. OpenType codes: assign this feature to languages <code>TRK, AZE, CRT, TAT, KAZ</code> of script <code>latn</code>.',
        tests: [
          '“kevgir” & “direk” always have dots',
          '“Işım” has no dots',
          '“haritacı” & “siyahımsı” have dots over the first i only',
        ],
      }
    ],
  },
  {
    language: 'Ukrainian',
    region: 'European',
    script: 'Cyrl',
    speakers: million(30),
    pangrams: ['Чуєш їх, доцю, га? Кумедна ж ти, прощайся без ґольфів! Жебракують філософи при ґанку церкви в Гадячі, ще й шатро їхнє п’яне знаємо.'],
    gotchas: [{
      topic: 'її',
      tags: ['metrics', 'ligature', 'optional'],
      description: 'The possible collision of dieresis in Ukrainian word <em>її</em> (‘her’) can be avoided by providing a ligature with three dots instead of four.',
      tests: ['ЗГОДОМ ЇЇ ВЖИВ без імени її творця. Ви вже бачили її нового друга? Обидві її дитини були шоковані від її нового друга, але змирилися з ситуацією, бо хотіли, щоб їх мама була щаслива.'],
    }],
  },
  {
    language: 'Vai',
    region: 'African',
    script: 'Latn',
    speakers: thousand(120),
    specialCharacters: 'Á Ã É Í Ó Õ Ú á ã é í ó õ ú Ĩ ĩ Ŋ ŋ Ũ ũ Ɓ  Ɔ  Ɗ Ɛ ɓ ɔ ɗ ɛ Ẽ ẽ',
  },
  {
    language: 'Vietnamese',
    region: 'Asian',
    script: 'Latn',
    speakers: million(76),
    pangrams: ['Do bạch kim rất quý nên sẽ dùng để lắp vô xương.'],
    gotchas: [{
      topic: 'horn diacritic',
      tags: ['metrics'],
      tests: ['lựt mưng nữi nựi nưm lưu'],
    }],
    specialCharacters: 'À Á Â Ã È É Ê Ì Í Ò Ó Ô Õ Ù Ú Ý à á â ã è é ê ì í ò ó ô õ ù ú ý Ă ă Đ đ Ĩ ĩ Ũ ũ Ơ ơ Ư ư Ạ ạ Ả ả Ấ ấ Ầ ầ Ẩ ẩ Ẫ ẫ Ậ ậ Ắ ắ Ằ ằ Ẳ ẳ Ẵ ẵ Ặ ặ Ẹ ẹ Ẻ ẻ Ẽ ẽ Ế ế Ề ề Ể ể Ễ ễ Ệ ệ Ỉ ỉ Ị ị Ọ ọ Ỏ ỏ Ố ố Ồ ồ Ổ ổ Ỗ ỗ Ộ ộ Ớ ớ Ờ ờ Ở ở Ỡ ỡ Ợ ợ Ụ ụ Ủ ủ Ứ ứ Ừ ừ Ử ử Ữ ữ Ự ự Ỳ ỳ Ỵ ỵ Ỷ ỷ Ỹ ỹ',
    paragraphs: ['Ảnh hưởng này kéo theo sự xuất hiện của nhiều từ gốc Pháp trong nhiều lĩnh vực khác nhau, đặc biệt là trong khoa học – kỹ thuật. Ễnh ương đốm.', `Tiếng Việt, còn gọi tiếng Việt Nam[5] hay Việt ngữ, là ngôn ngữ của người Việt (người Kinh) và là ngôn ngữ chính thức tại Việt Nam. Đây là tiếng mẹ đẻ của khoảng 85% dân cư Việt Nam, cùng với hơn bốn triệu người Việt hải ngoại. Tiếng Việt còn là ngôn ngữ thứ hai của các dân tộc thiểu số tại Việt Nam. Mặc dù tiếng Việt có một số từ vựng vay mượn từ tiếng Hán và trước đây dùng chữ Nôm — một hệ chữ dựa trên chữ Hán — để viết nhưng tiếng Việt được coi là một trong số các ngôn ngữ thuộc ngữ hệ Nam Á có số người nói nhiều nhất (nhiều hơn một số lần so với các ngôn ngữ khác cùng hệ cộng lại). Ngày nay, tiếng Việt dùng bảng chữ cái Latinh, gọi là chữ Quốc ngữ, cùng các dấu thanh để viết.`,
      `Tiếng Việt được chính thức ghi nhận trong Hiến pháp nước Cộng hòa Xã hội chủ nghĩa Việt Nam 2013, tại chương I điều 5 mục 3, là ngôn ngữ quốc gia của Việt Nam [6]. Tiếng Việt bao gồm cách phát âm tiếng Việt và chữ Quốc ngữ để viết. Tuy nhiên hiện chưa có bất kỳ văn bản nào ở cấp nhà nước quy định giọng chuẩn và quốc tự của tiếng Việt [7]. Hiện nay phần lớn các văn bản trong nước được viết theo những "Quy định về chính tả tiếng Việt và về thuật ngữ tiếng Việt" áp dụng cho các sách giáo khoa, báo và văn bản của ngành giáo dục nêu tại Quyết định của Bộ Giáo dục số 240/QĐ ngày 5 tháng 3 năm 1984 [8] do những người thụ hưởng giáo dục đó sau này ra làm việc trong mọi lĩnh vực xã hội.`, `Cũng cần lưu ý tránh nhầm lẫn với Việt ngữ (粵語) hay tiếng Quảng Đông, một ngôn ngữ được sử dụng ở miền nam Trung Quốc (Quảng Đông, Quảng Tây) cũng như ở Hồng Kông và Ma Cao.`, `Tổ chức tiêu chuẩn hóa quốc tế đặt mã ngôn ngữ hai chữ cái cho tiếng Việt là "vi" (tiêu chuẩn ISO 639-1) và đặt mã ngôn ngữ ba chữ cái cho tiếng Việt là "vie" (tiêu chuẩn ISO 639-2) [9][10][11].`
    ],
  },
  {
    language: 'Walser German',
    // htmlTag: 'wae',
    // opentypeTag: 'DEU',
    altNames: ['Walser', 'Walliser German', 'Walliser', 'Walserdeutsch', 'Walliserdeutsch'],
    region: 'European',
    speakers: thousand(22),
    pangrams: ['«Méin oalten atte ischt gsinh van in z’Überlann, un d’oaltun mamma ischt van Éischeme, ischt gsing héi van im Proa. Stévenin ischt gsinh dar pappa, la nonna ischt gsinh des Chamonal. [...] D’alpu ischt gsinh aschua van méin oalten pappa. Ich wiss nöit ol z’is heji... Ischt gsinh aschuan d’oaltu, un d’ketschu, gmachut a schian ketschu in z’Überlann.»'],
  },
  {
    language: 'Welsh',
    region: 'European',
    speakers: thousand(700),
    pangrams: ['Parciais fy jac codi baw hud llawn dŵr ger tŷ Mabon. John Rhŷs. ẂẃẀẁŴŵẄẅ ÝýỲỳŶŷŸÿ'],
  },
  {
    language: 'Central Yambasa',
    altNames: ['Yangben'],
    region: 'African',
    speakers: thousand(17),
    specialCharacters: 'À Á Â È É Ì Í Î Ò Ó Ô Ù Ú Û à á â è é ì í î ò ó ô ù ú û Ā ā Ī ī Ŋ ŋ Ō ō Ū ū Ɔ Ɛ Ǎ ǎ Ǒ ǒ Ǔ ǔ ɔ ɛ',
  },
  {
    language: 'Yoruba',
    region: 'African',
    speakers: million(28),
    pangrams: ['Ìwò̩fà ń yò̩ séji tó gbojúmó̩, ó hàn pákànpò̩ gan-an nis̩é̩ rè̩ bó dò̩la.'],
  },
  {
    language: 'Zarma',
    region: 'African',
    speakers: million(3.5),
    pangrams: ['Da curo fo hẽ, afo mana hẽ, i si jinde kaana bay. Ay no leemuyaŋ. '],
    specialCharacters: 'Ã Õ ã õ Ŋ ŋ Š š Ž ž Ɲ ɲ Ẽ ẽ',
  },
  {
    language: 'Zulu',
    region: 'African',
    speakers: million(12),
    pangrams: ['Thina, bantu baseNingizimu Afrika, Siyakukhumbula ukucekelwa phansi kwamalungelo okwenzeka eminyakeni eyadlula;  Sibungaza labo abahluphekela ubulungiswa nenkululeko kulo mhlaba wethu;  Sihlonipha labo abasebenzela ukwakha nokuthuthukisa izwe lethu; futhi  Sikholelwa ekutheni iNingizimu Afrika ingeyabo bonke abahlala kuyo, sibumbene nakuba singafani.'],
    specialCharacters: "",
  },
  {
    language: 'IPA',
    htmlTag: '',
    opentypeTag: '',
    script: 'IPA',
    speakers: 0,
    specialCharacters: 'ʃ θ ʊ ʊ ʌ ʒ ʔ æ ɑ ð ə ɚ ɛ ɜ ɝ ɪ ɫ ŋ ɔ ɒ ɹ ɾ ˈ ˌ ː ᵊ ʳ õ r̩',
    paragraphs: ['/sɯ̥ʃi/ /a̠ˈmiɣo̟/ [ˈɲeɣʐɛ] [ðə bɛɪʒ çjuː ˈɒn ðə wɔːtəz əv ðə lɔx ɪmˈprɛst ɔːl ɪnˈkluːdɪŋ ðə frɛntʃ kwiːn bɪˈfɔː ˈʃiː hɜːd ðæt ˈsɪɱfəni əˈɡɛn dʒəst əz jʌŋ ˈɑːθə ˈwɒntɪd]',
      '/à ˈnojtɨ, vuˈvo kuuaɫʃˈki ˈve u ˈimɐ̃ kɐˈiɾ nu ˈpɛ du ˈpĩgüˈĩ kɐjˈʃozu i vuˈvɔ ˈpõj ɐˈsukaɾ nu ˈʃa dɨ ˈtɐmɐɾɐʒ du ʒɐbuˈti fɨˈɫiʃ/',
      '[ˈxoˈse kõmˈpɾo ˈuna ˈβjexa sãmˈpoɲa ɛ̃m pɛˈɾu ɛksuˈsãn̪dose, soˈfia tiˈɾo su ˈwiskj al̪ deˈsaɣwe ðe la βãŋˈkɛta]',
      ' maj ˌɹɛvəˈleʃənz æz ə spaj ˈstivən ˈliˌkɑk  ( fɹəm ˈfɹɛnzid ˈfɪkʃən )  ɪn ˈmɛni ˈpipəl ðə ˈvɛɹi nem "spaj " əkˈsajts ə ˈʃʌdəɹ əv ˌæpɹəˈhɛnʃən ; wi spajz , ɪn fækt , ɡɛt kwajt just tə ˈbiɪŋ ˈʃʌdəɹd æt . nʌn əv ʌs spajz majnd ət æt ɑl . ˌwɛnˈɛvəɹ aj ˈɛntəɹ ə ˌhoˈtɛl ənd ˈɹɛdʒəstəɹ ˌmajˈsɛlf æz ə spaj aj əm kwajt əˈkʌstəmd tə si ə θɹɪl əv fɪɹ ɹʌn ɹawnd ðə kləɹks , ɔɹ kləɹk , bəˈhajnd ðə dɛsk .  ʌs spajz , ɔɹ wi spajz --fɔɹ wi kɑl ɑɹˈsɛlvz boθ --ɑɹ ðʌs ə ɹes əˈpɑɹt . nʌn no ʌs . ɑl fɪɹ ʌs . wɛɹ du wi lɪv ? ˈnoˌwɛɹ . wɛɹ ɑɹ wi ? ˈɛvɹiˌwɛɹ .',
      'ˈfɹikwəntli wi dont no ɑɹˈsɛlvz wɛɹ wi ɑɹ . ðə ˈsikɹət ˈɔɹdəɹz ðət wi ɹəˈsiv kʌm fɹəm so haj ʌp ðæt ɪt ɪz ˈɑfən fʌɹˈbɪdən tu ʌs ˈivən tə æsk wɛɹ wi ɑɹ . ə fɹɛnd əv majn , ɔɹ æt list ə ˈfɛlo spaj --ʌs spajz hæv no fɹɛndz --wʌn əv ðə most ˈbɹɪljənt mɛn ɪn ðə hʌŋˈɡɛɹiən ˈsikɹət ˈsəɹvəs , wʌns spɛnt ə mʌnθ ɪn ˌnju ˈjɔɹk ˈʌndəɹ ðə əmˈpɹɛʃən ðət hi wəz ən ˈwɪnəˌpɛɡ . ɪf ðɪs ˈhæpənd tə ðə most ˈbɹɪljənt , θɪŋk əv ðə ˈʌðəɹz .  ðə ˈsɔɹoz əv ə ˈsʌməɹ ɡɛst  lɛt mi ədˈmɪt , æz aj stɑɹt tə ɹajt , ðət ðə hol θɪŋ ɪz maj fɑlt . aj ʃʊd ˈnɛvəɹ həv kʌm , aj nju ˈbɛtəɹ . aj həv non ˈbɛtəɹ fɔɹ jɪɹz . aj hæv non ðət ɪt əz ʃɪɹ ˈmædnəs tə ɡo ənd pe ˈvɪzəts ɪn ˈʌðəɹ ˈpipəlz ˈhawzəz .  jɛt ɪn ə ˈmomənt əv ɪnˈsænəti aj həv lɛt ˌmajˈsɛlf ˈɪn fəɹ ɪt ənd hɪɹ aj æm . ðɛɹ ɪz no hop , no ˈawtlət naw tɪl ðə fəɹst əv ˌsɛpˈtɛmbəɹ wɛn maj ˈvɪzət ɪz tə ˈtəɹməˌnet . ˈajðəɹ ˈðæt ɔɹ ˈdɛθ . aj du nɑt ˈɡɹetli kɛɹ wɪtʃ .',
    ],
  },
  ];
}